# Generated by Django 3.1.4 on 2020-12-07 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_number', models.PositiveIntegerField(blank=True, default=None, help_text='Enter the board number of the vehicle', null=True)),
                ('transport_type', models.CharField(choices=[('air', 'Aircraft'), ('bus', 'Bus'), ('tbus', 'Trolleybus'), ('train', 'Train'), ('tram', 'Tram')], default='bus', help_text='Select the type of transport', max_length=5)),
            ],
            options={
                'verbose_name': 'Transport',
                'verbose_name_plural': 'Transports',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Enter route number', max_length=100)),
                ('route_type', models.CharField(choices=[('air', 'Aircraft'), ('bus', 'Bus'), ('tbus', 'Trolleybus'), ('train', 'Train'), ('tram', 'Tram')], default='bus', help_text='Select the type of transport route', max_length=5)),
                ('transports', models.ManyToManyField(to='transport_routes.Transport')),
            ],
            options={
                'verbose_name': 'Route',
                'verbose_name_plural': 'Routes',
            },
        ),
    ]
