# Generated by Django 3.1.4 on 2020-12-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
