# Generated by Django 3.1.4 on 2020-12-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='number',
            field=models.PositiveSmallIntegerField(default=None, help_text='Enter route number'),
        ),
    ]
