# Generated by Django 3.1.4 on 2020-12-07 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_routes', '0002_route_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='board_number',
            new_name='vehicle_id_number',
        ),
        migrations.AddField(
            model_name='transport',
            name='description',
            field=models.CharField(blank=True, help_text='Enter a description of the transport', max_length=100, null=True),
        ),
    ]
